### ISSUE TITLE
Documentations and tutorials are out-of-dated

### ISSUE THREAD

**Issue by ntung** [saezlab/pypath#104]
Our team [EMBL-EBI/BioModels] has a trainee who is using your modules in her experiments. We are having a chance to work together to push the work forward. What we have found is that the tutorials, as well as a sample of the so-called hello world program, do not match with the library.

Let's give an example.

Following the instructions on [1], we install the module from the git repository. Then, try to test the installation with a piece of code you consulted in Tutorials section. It doesn't work.

The same problem we encountered if get through the official references of the library published at [2] because we're aware of the fact that this documentation is used for version 0.5.

We found jupyter notebook document at [3] that was useful, however, this page was directed from the homepage [1].

What I anticipate that once the documentation is published, try to keep updated as much as you can.

All the best,

[1] http://omnipathdb.org/
[2] http://pypath.omnipathdb.org/
[3] http://pypath.omnipathdb.org/notebooks/pypath_guide.html

**Comment by deeenes** [comment]
Hi,

Thanks good point! I updated the docs at http://pypath.omnipathdb.org/.
Also we are working towards reaching a higher coverage.
Indeed the "pypath guide" tutorial is the most up-to-date at the moment.

Best,

Denes

**Comment by deeenes** [comment]
I'm closing this because since then we achieved a great progress in documentation, especially with the new "[Pypath book](https://pypath.omnipathdb.org/)". And the [reference docs](https://pypath.omnipathdb.org/reference.html) are much more complete too. We don't really have the capacity to maintain an ideal level of docs coverage and update speed, so I can't promise more at the moment.
