### ISSUE TITLE
dependencies

### ISSUE THREAD

**Issue by gabora** [saezlab/pypath#108]
the following packages were missing by the time of importing pypath. 
Could you tell pip to install the following dependencies?
- fabric
- pysftp
- grin/argparse   (grin 1.2.1 requires argparse>=1.1, which is not installed.)

**Comment by deeenes** [comment]
These modules are not in the dependencies because many users don't need them, e.g. only the dowload of a single, not commonly used resource requires them. And I wanted to avoid installing dozens of third party modules by default. We send log messages about the missing modules and the user can install them manually. Do you get any `ModuleNotFoundError` with the most recent `pypath`? At which line? Do you think it's better to add them as dependency? My aim is to make even `cairo` and `igraph` optional dependencies.

**Comment by gabora** [comment]
Hi
thanks, I think `pypath` gives a nice feedback on `pysftp` - so the user knows that skipping it is not a main problem. But it just reports that `fabric` was not found, and I dont really know the consequences.
`grin/argparse` was reported during the installation with `pip`. 

right now I am checking the other issue, that I submitted. Maybe there is a version problem because of interference between pip and conda. :/

**Comment by gabora** [comment]
sorry, actually I found this piece of info in the Installation section of the repo.
