### ISSUE TITLE
module 'pypath.reflists' has no attribute 'get_reflists'

### ISSUE THREAD

**Issue by qiiiibeau** [saezlab/pypath#118]
Hello, 
I wanted to create a PyReact object but failed. The class PyReact has an attribute load_reflists() which called the function reflists.get_reflists()
However, in reflists.py there's no get_reflists() function. There's a get_reflist() function to the contrary. 
Is this a typo error?
```
import pypath.pyreact as pyreact
paths = pyreact.PyReact()
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "/home/qsun/git_space/networks-2019/venv/lib/python3.7/site-packages/pypath/pyreact.py", line 1015, in __init__
    self.load_reflists()
  File "/home/qsun/git_space/networks-2019/venv/lib/python3.7/site-packages/pypath/pyreact.py", line 2211, in load_reflists
    reflst = reflists.get_reflist()
AttributeError: module 'pypath.reflists' has no attribute 'get_reflists'

```

**Comment by deeenes** [comment]
Hi Qiiiibeau,

The `pyreact` module we used for the paper in 2016 and since then while all the other modules in `pypath` have been largely redesigned or completely rewritten. At the same time we have plans for a completely different processing of the "process description" resources in order to make a real use of their data and this will mean a substantial redesign of the `pyreact` module.

Bc of the reasons above initially I wanted to answer you sorry we don't support `pyreact` at the moment. But once I quickly checked the error, I could make it work after fixing a few other trivial errors. I was able to load all the 7 built in process description resources with version `0.8.47`:

http://pypath.omnipathdb.org/releases/archive/

Or you can install from the tip of the `dev` branch.

 I haven't tried to do anything with them apart from loading, I have no idea if those methods work.

Best,

Denes

**Comment by deeenes** [comment]
Closing this, you can open a new one if other errors come up :)
