### ISSUE TITLE
Problems with interpreting Signor interactions

### ISSUE THREAD

**Issue by willov** [saezlab/pypath#15]
Following the intro from here: http://pypath.omnipathdb.org/notebooks/intro.html

After downloading Signor interactions,  I get warnings saying "Line x has less than 22 fields, skipping".
When I check the cached file, the file does have more than 22 fields. 

Going into Main.py and printing the lines in the if statement at line 1220 (if len(line) < maxCol), the lines have \t as delimiter, but settings.separator is None. I assume this is the issue. 
Tried to find where settings.separator is set, but did not find where this was done. 

This was run on a fresh download from GitHub of latest version downloaded 17th of January, with Anaconda on Ubuntu 16.10. 

I've attached my log file and my test script
[test.txt](https://github.com/saezlab/pypath/files/1642350/test.txt)
[2788j.log](https://github.com/saezlab/pypath/files/1642242/2788j.log)

**Comment by deeenes** [comment]
Dear Willov,

Indeed there was a format change in Signor, previously they used a semicolon now they have tabs in their table. I updated accordingly, 0.7.59 (or latest git) should work. I hope it works for you and thanks for spotting this.

The `settings.separator` is `None` because the data here is preprocessed by another method (`pypath.dataio.signor_interactions()`) so when building the network we already don't need to care about the separator.

Best,
Denes

**Comment by willov** [comment]
Great job, really quick! 
I pulled the changes and it seems to be working correctly now. 
I will keep testing, and report new issues if I spot any!
