### ISSUE TITLE
Mac install

### ISSUE THREAD

**Issue by ayadlin** [saezlab/pypath#155]
I attempted to install on my Mac
The full install process was completed, but when i do

from pypath import main

the following error arises:

ImportError                               Traceback (most recent call last)
<ipython-input-2-202a268b4a12> in <module>
----> 1 from pypath import main

ImportError: cannot import name 'main' from 'pypath' (/Users/ale/anaconda3/envs/bioinfo/lib/python3.7/site-packages/pypath/__init__.py)

I double checked I was in the right environment. Any advice is appreciated

**Comment by Nic-Nic** [comment]
Dear @ayadlin 

This is because there is not any submodule named `main` in pypath. Perhaps what you are looking for is the submodule named `core`? We recently refactored the module structure so the tutorials/documentation can be outdated in some sections and we are working on updating them. Sorry for any inconvenience.
Cheers,

Nico

**Comment by deeenes** [comment]
Hi @ayadlin,

The `main` contains a legacy, `igraph` based implementation of the network database. To access it, do `from pypath.legacy import main`. To access the current network API do `from pypath.core import network`.

Best,

Denes

**Comment by ayadlin** [comment]
Thank you-
Yes I was following the tutorials I’ll move to core.
Thanks-

Ale
