### ISSUE TITLE
OmniPath's CellChatDB is 500 larger than the original CellChatDB

### ISSUE THREAD

**Issue by dbdimitrov** [saezlab/pypath#174]
Hi @deeenes,

I noted an issue with the number of interactions that we obtain when using OmniPathR is 2571, while the original interactions list which you can access via `CellChat::CellChatDB.human$interaction` is 1931.

When queried via:

`import_intercell_network(transmitter_param = list(resource = "CellChatDB"),
                         reciver_param = list(resource = "CellChatDB"),
                         resources = "CellChatDB")`

2022 interactions are returned.

Thus, I think that the larger number might be an artifact of the conversions in `ligrec_decoupler`, possibly associated with co-factors being treated as receivers and transmitters.

Best,

Daniel

**Comment by deeenes** [comment]
Looking at the code in `pypath.inputs.cellchatdb`, the extra interactions are from the expansion of cofactors. CellChatDB data consists of 4 data frames: interactions, complexes, cofactors and genes. The interactions we process into interacting ligand receptor pairs, many of the involve complexes, here we can lose or gain a few records only due to failed or ambiguous ID translation. Then, some interaction rows refer to cofactors. For these, we take the list of the cofactors and add interactions from each of the cofactors to the ligand or receptor (depending whether it's an agonist, antagonist or coreceptor). For example, TGFb agonists (FST and THBS1) are cofactors for TGFB1, hence we add 2 extra interactions, FST -> TGFB1 and THBS1 -> TGFB1.

These cofactors are annotated as "ligand regulators" or "receptor regulators". These are all transmitters i.e. are able to deliver information from the expressing cells to outside of those cells. You might wonder why the receptor regulators, which are coreceptors here, are transmitters. I think because even if these are in the membrane of the expressing cell, their role is more similar to autocrine signaling, they act on the receptors of the cell itself, and they cannot be receivers as they don't actually deliver signal from outside into the expressing cell.

The CellChatDB authors collected the cofactors from KEGG pathway diagrams. They cannot guarantee that all cofactors indeed have an effect on all ligands and receptors where they are listed. Hence the expansion of these interactions might introduce some false positives.

**Comment by deeenes** [comment]
One point we can improve here is not to add the literature references to these expanded interactions. This way downstream quality filters will remove more of them. I've done it in fece6808, this change will propagate to the web service data at the next database build.

**Comment by dbdimitrov** [comment]
I noticed that CellChatDB is now 2551 interactions once we query it, i.e. an exact match to the original. So, I would assume that this issue is now resolved.

The point about mediators simply being involved in autocrine signalling is rather fascinating, I have not thought about it in that direction. Also, given that the mediators in CellChat are KEGG annotated, it might be relevant to also extend my CellChatDB conversions to include interactions from the PPI from OmniPath.

Much appreciated @deeenes
