### ISSUE TITLE
Can't find direction/sign between two nodes

### ISSUE THREAD

**Issue by marieBvr** [saezlab/pypath#23]
Hello,
 I am trying to extract direction and sign from a network.
```
import pypath
from pypath import curl
from pypath import data_formats

pa = pypath.PyPath()
with curl.cache_off():
   pa.load_resources(data_formats.pathway)
list(pa.gs_inhibited_by('MYC').gs())
# One of the result is STAT1
# I want to verify the direction and sign between MYC and STAT1
pa.graph.es[pa.get_edge(pa.gs('MYC'), pa.gs('STAT1'))]['dirs']
```
The last command render me:
`TypeError: igraph supports string attribute names only, got <type 'NoneType'>`
It seems like there is no edge between MYC and STAT1 despite STAT1 was listed as a node inhibited by MYC.

Is there something I did wrong ?

Best,
 @Marie

**Comment by deeenes** [comment]
Hi Marie,

STAT1 down-regulates MYC according to the SPIKE database, they got the information from http://www.ncbi.nlm.nih.gov/pubmed/10637230.

Actually there is only a little issue with your code: ``pa.gs('STAT1')`` returns ``igraph.Vertex`` object while ``get_edge`` accepts only integer vertex IDs, UniProt IDs or gene symbols. Maybe later I will modify it to accept the vertex objects too. And also you don't need ``pa.graph.es`` because ``get_edge`` already returns ``igraph.Edge`` object. In summary you can do like this:

```
>>> print(pa.get_edge('STAT1', 'MYC')['dirs'])
Directions and signs of interaction between P01106 and P42224

	P01106 <=== P42224 :: SPIKE
	P01106 <=-= P42224 :: SPIKE
```

Best,

Denes
