### ISSUE TITLE
Link in pypath to unichem seems broken

### ISSUE THREAD

**Issue by pluthert** [saezlab/pypath#299]
Trying to create knowledge graph using Metalinks

'metalinks % python create_knowledge_graph.py'

Generates error...
  File "/Users/tonyrainbow/Library/Caches/pypoetry/virtualenvs/metalinks-9dfoHN-W-py3.11/lib/python3.11/site-packages/pypath/inputs/unichem.py", line 59, in unichem_info
    soup = bs4.BeautifulSoup(c.result, 'html.parser')
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/tonyrainbow/Library/Caches/pypoetry/virtualenvs/metalinks-9dfoHN-W-py3.11/lib/python3.11/site-packages/bs4/__init__.py", line 315, in __init__
    elif len(markup) <= 256 and (
         ^^^^^^^^^^^
TypeError: object of type 'NoneType' has no len()

It looks like the problem is that the link to Unichem Sources isn't working. It also appears as though the Unichem site has changed but my attempts to fix have failed, sorry!

 - MacOS 14.1
 - Python 3.11

**Comment by pluthert** [comment]
Hi, I seem to have sorted this. The problem appears to be that the EBI UniChem legacy site is no longer accessible. Replacing the URL at line 1484 in urls.py with 'https://www.ebi.ac.uk/unichem/api/v1/sources/' seems to work.

**Comment by pluthert** [comment]
Hi
First thanks so much for getting back in touch and, of course, for the great code. I am a novice but learning a great deal from you all! I may have confused things. I accessed PyPath from Metalinks. From the log (pasted below) it looks like version 0.15.13. Does that make sense?
Thanks again.
Best
Phil


[2024-12-14 18:30:01] Welcome!
[2024-12-14 18:30:01] Logger started, logging into `/Users/tonyrainbow/metalinks/pypath_log/pypath-092vf.log`.
[2024-12-14 18:30:01] Session `092vf` started.
[2024-12-14 18:30:01] [pypath]
      - session ID: `092vf`
      - working directory: `/Users/tonyrainbow/metalinks`
      - logfile: `/Users/tonyrainbow/metalinks/pypath_log/pypath-092vf.log`
      - pypath version: 0.15.13
________________________________

**Comment by npalacioescat** [comment]
Hi @pluthert,
I see... so, if I'm not mistaken, it seems that you're accessing PyPath through [this repo](https://github.com/biocypher/metalinks). It seems from the package configuration files
([here](https://github.com/biocypher/metalinks/blob/68d15ad59261286074224a91656b51344d7d733e/pyproject.toml#L14) and [here](https://github.com/biocypher/metalinks/blob/68d15ad59261286074224a91656b51344d7d733e/env.yml#L61)) that they are using an [outdated branch from a fork of PyPath](https://github.com/dbdimitrov/pypath/tree/metalinks).
If this is the case, one option is that `biocypher/metalinks` updates their dependency configuration so that it points to the current version of PyPath. The other option is that the [branch from the fork that metalinks is using](https://github.com/dbdimitrov/pypath/tree/metalinks) updates to the current version of PyPath (or implements the fix of the URL).
You can try to open an issue at [`biocypher/metalinks`](https://github.com/biocypher/metalinks) to request this update as this error is already fixed in the current version of PyPath.

Cheers

**Comment by dbdimitrov** [comment]
Hi both,

@npalacioescat, thanks a lot for looking into this. I just wanted to mention that at some point, Elias and I did try to update pypath, but there were other issues with the updated version, that's why we used a frozen fork.

@pluthert, not sure if reproducing the generation process of metalinks is necessary for your purposes. If access to it is suffient, we provide easy programmatic acess via liana: https://liana-py.readthedocs.io/en/latest/notebooks/prior_knowledge.html#Metabolite-Receptor-Interactions, and you could also write your own neo4j/sql queries on the deposited DB dumps: https://zenodo.org/records/10200150 or https://figshare.com/ndownloader/files/47567597
