### ISSUE TITLE
Bug on main.PyPath.all_between()

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/pypath#5]
Got a TypeError when calling all_between function. 
I think that in line 2356 (src/pypath/main.py of v0.7.3), when calling self.edge_exists(), _self_ should not be passed as an argument since it is a function of the same instance.
```eid = self.edge_exists(self, nameA, nameB)```
should be:
```eid = self.edge_exists(nameA, nameB)```

**Comment by deeenes** [comment]
thanks Nic-Nic, you are right! fixed in 0.7.5 and in git. http://pypath.omnipathdb.org/releases/archive/
see also `get_edge` and `get_edges` method, and many others with names like `get_node`, `get_nodes`, `get_node_d`, `up`, `gs`, `neighbors`, `gs_neighbors`, `stimulated_by`, `affects`, etc (maybe one of these is more suitable for you).
