### ISSUE TITLE
AnnotationTable class

### ISSUE THREAD

**Issue by Nic-Nic** [saezlab/pypath#87]
Since 893fb9c, `AnnotationTable` class has no attributes `names` or `uniprots` and therefore many of its methods are not working anymore (e.g. `to_dataframe()`). Is this intentional, did the attribute names changed?

**Comment by deeenes** [comment]
Yes it was intentional, because the same instance handles protein and complex annotations, hence it has reference lists with all proteins and all complexes or both together. Also I modified the annotation fields used by default and excluded Human Protein Atlas from this boolean array. This way the `to_array` and `to_dataframe` methods work and run in approx 8 min. However I am not sure we will need often the boolean array. Overall the issue should be fixed by ab8ae3b

**Comment by Nic-Nic** [comment]
Still undefined `self.uniprots` attribute that's trying to set the indices of the dataframe :/

**Comment by deeenes** [comment]
Sorry, I think this fixes it finally: c7c8c9c

**Comment by Nic-Nic** [comment]
Solved! Thanks :)
