### ISSUE TITLE
Omnipath loading error

### ISSUE THREAD

**Issue by luli7** [saezlab/pypath#90]
Dear Omnipath Developers,

I have installed pypath (0.8.9) under python 3.6, in Ubuntu18.04.
when I run load_omipath(), I got the following error.
Could you please help me to identify the problem and solutions? 
Thank you in advance.
Lu

>>> pa.load_omnipath()
  File "/usr/local/lib/python3.6/dist-packages/pypath/main.py", line 2312, in read_data_file
    infile = input_func(**param.input_args)
  File "/usr/local/lib/python3.6/dist-packages/pypath/dataio.py", line 8981, in get_dip
    for l in f:
[2019-06-05 08:23:38] [network] `get_dip`: Could not find file or dataio function or failed preprocessing.

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pypath/main.py", line 12821, in load_omnipath
    self.third_source_directions()
  File "/usr/local/lib/python3.6/dist-packages/pypath/main.py", line 12945, in third_source_directions
    self.kegg_directions(graph=graph)
  File "/usr/local/lib/python3.6/dist-packages/pypath/main.py", line 12962, in kegg_directions
    keggd = dataio.get_kegg()
  File "/usr/local/lib/python3.6/dist-packages/pypath/dataio.py", line 6892, in get_kegg
    kgmlsoup = bs4.BeautifulSoup(kgml, 'html.parser')
  File "/usr/lib/python3/dist-packages/bs4/__init__.py", line 192, in __init__
    elif len(markup) <= 256 and (
TypeError: object of type 'NoneType' has no len()

**Comment by deeenes** [comment]
Hi Lu,

The first error was due to an outdated URL to DIP, I fixed it in e4c2a50, version 0.8.12.

The second one which actually raises an exception, is due to KEGG. I am investigating this, because I could download an XML from KEGG like 30 min ago, but now it only returns empty responses (the direct cause of the error). I need to find out whether this is an error on their side, or they want to disable this way bulk downloads, or I miss some HTTP header.

Meanwhile you could disable the `PyPath.kegg_directions` method, unfortunately there is no option for that, maybe if you overwrite it with an empty method:

```
pa.kegg_directions = lambda graph: None
```

Best,

Denes

**Comment by luli7** [comment]
Hi Denes,

Thank you very much for the help, I will update my pypath and try to bypass kegg.
I  realise there is another method to load Omnipath (other than: pa.load_omnipath()):
pa.init_network()
It has been running quite a while without giving me  error message so far, I will wait and see.

what are the differences between these two methods? 

I am trying to learn pypath via http://pypath.omnipathdb.org/ , which is documenting for pypath 0.5. Are there lots of changes in pypath 0.8+ ?

I have also a general question. I always thought Omnipath is a manually curated pathway/network. So I expected it to be relatively "static". However now I feel it has been built dynamically every time when we initiate network in pypath. Am I right? Is there a way to down load Omnipath without using pypath?

Thank you very much again for your help.
Best regards
Lu

**Comment by deeenes** [comment]
The KEGG issue above fixed in 7be75e2, thanks to @gabora

**Comment by deeenes** [comment]
Hi Lu,

There are quite some changes since 0.5 and it results confusion that the tutorials are outdated. I just created a new one: http://pypath.omnipathdb.org/notebooks/pypath_guide.html

Pypath builds the network from the original sources, it does not contain data itself (apart from a few exceptions). Many of the resources updates their content time to time, while many others don't change already for long time. OmniPath is mostly manually curated, but it contains also other datasets.

Best,

Denes
