### ISSUE TITLE
[dataio] Module `bioservices` not available.

### ISSUE THREAD

**Issue by mglont** [saezlab/pypath#94]
OS: RedHat 7.3
Anaconda 4.6.14
Python 3.7.3
pypath 0.8.18

I created a fresh anaconda environment and installed pypath with the following steps:
```
pip install python-igraph
conda install pygraphviz pycairo
pip install git+git://github.com/saezlab/pypath.git
# fixup for libcurl version mismatch ( libcurl link-time version (7.29.0) is older than compile-time version (7.64.1))
conda install pycurl
```

It installed fine, but then when I tried ```from pypath import main``` I got an error message saying

```
[2019-06-17 21:38:30] [dataio] Module `bioservices` not available.
```

```
pa = main.PyPath()
pa.load_omnipath()
```

seems to hang -- how long does it take for that call to complete?

**Comment by deeenes** [comment]
Hi Mihai,

The message you have seen is only for your information, we don't rely on `bioservices` in almost anything, we will soon remove it even as an optional dependency.

`load_omnipath` might take 40 min to 1-2 hours or even more, because for the complete build we download dozens or hundreds of resources, and also on your disk the cache content might grow to few GBs. Important to have a reliable network connection along the whole process. This happens at the very first build, after then `pypath` reads the data from its cache directory. However `load_omnipath` comes with quite some data processing, hence it takes like 30 min even if you have everything in your cache. During the network build you see many log messages about the files downloaded or accessed and the resources added.

If it fails, no worries, the cache content is still available so your next attempt won't take so long.

The kind of error we see the most often is failed downloads, due to poor network connection or third party server downtime.

You can also test it with a smaller dataset, e.g. loading only one resource:

```
from pypath import main, data_formats

pa = main.PyPath()
pa.init_network({'signor': data_formats.pathway['signor']})
```

Once you have built a network you can save it to a pickle file and loading from there takes only few seconds:

```
pa.save_network(pfile = 'mynetwork.pickle')

# and loading it:
pa = main.PyPath()
pa.init_network(pfile = 'mynetwork.pickle')
```

Best,

Denes

**Comment by mglont** [comment]
That smaller example worked a treat, @deeenes, many thanks for the clear explanation.
