### ISSUE TITLE
igraph node "name" and "label" show the same thing

### ISSUE THREAD

**Issue by jadeshi** [saezlab/pypath#97]
Hi, I just tried installing the latest version of pypath and loading a sample graph using the pathway resources. I notice now that for each node in the graph, the "name" and "label" now both give the same thing, whereas previously when I was using an older version, "label" would show the more conventional symbol for the gene, e.g.

vertex['name'] would give 'P63000',
vertex['label'] would give 'RAC1'

Now both options give 'P63000'. I'm wondering, is there an easy way to fetch the gene labels? Thanks!

**Comment by deeenes** [comment]
Hi Jade,

The `label` attribute is created by the `PyPath.genesymbol_labels` method. It falls back to the value of `name` (UniProt for proteins) if the ID translation fails. You could check if the ID translation module translates properly from UniProt to Gene Symbols:

```
from pypath import mapping
mapping.map_name('P00533', 'uniprot', 'genesymbol')
# returns {'EGFR'}
```

Most likely the example above will also fail for you as probably the translation table is empty due to an earlier download failure. You can fix this by downloading it again from UniProt:

```
from pypath import curl, mapping
with curl.cache_off():
    mapping.map_name('P00533', 'uniprot', 'genesymbol')
```

If this is successful, the data newly downloaded from UniProt has overwritten the wrong file in the cache, hence it will certainly work until your next cache update.

Best,

Denes

**Comment by jadeshi** [comment]
Ah, yes this was a dumb mistake on my part. I think at one point I terminated pypath while it was in the process of downloading the data so it didn't download everything it needed to. Clearing the cache and redownloading did the trick. Thanks!
